ALTER TABLE "Offer" ADD COLUMN "statusReason" TEXT;

ALTER TYPE "OfferStatus" RENAME TO "OfferStatus_old";

CREATE TYPE "OfferStatus" AS ENUM (
  'PENDING_VALIDATION',
  'REJECTED_INVALID_DATA',
  'REJECTED_EXPIRED',
  'REJECTED_DUPLICATE',
  'REJECTED_LOW_SCORE',
  'QUARANTINED_INTEGRATION_ERROR',
  'READY_TO_PUBLISH',
  'SCHEDULED',
  'PUBLISHED',
  'PUBLICATION_FAILED'
);

ALTER TABLE "Offer" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Offer" ALTER COLUMN "status" TYPE "OfferStatus" USING ("status"::text::"OfferStatus");
ALTER TABLE "Offer" ALTER COLUMN "status" SET DEFAULT 'PENDING_VALIDATION';

DROP TYPE "OfferStatus_old";
