import { z } from "zod";
import type { ShopeeBrazilRow, ShopeeDatafeedProduct } from "./types";
import { normalizeShopeeDatafeedRecord } from "./validation";

export const SHOPEE_ITEM_FEED_MAX_PAGE_SIZE = 500;
export const SHOPEE_OFFICIAL_FEED_CONTRACT = "OFFICIAL_V2_FULL" as const;

export const ShopeeFeedModeSchema = z.enum(["FULL", "DELTA"]);
export type ShopeeFeedMode = z.infer<typeof ShopeeFeedModeSchema>;

const safeInt64 = z
  .union([
    z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),
    z.string().regex(/^\d+$/),
  ])
  .transform((value, context) => {
    const parsed = typeof value === "number" ? value : Number(value);
    if (!Number.isSafeInteger(parsed) || parsed < 0) {
      context.addIssue({ code: "custom", message: "unsafe Int64" });
      return z.NEVER;
    }
    return parsed;
  });

const feedIdentifier = z.string().trim().min(1).max(256);
const feedDate = z
  .string()
  .trim()
  .regex(/^(?:\d{8}|\d{4}-\d{2}-\d{2})$/);

export const ShopeeOfficialFeedSchema = z
  .object({
    datafeedId: feedIdentifier,
    referenceId: feedIdentifier,
    datafeedName: z.string().trim().min(1).max(256),
    description: z.string().max(2_000),
    totalCount: safeInt64,
    date: feedDate,
    feedMode: ShopeeFeedModeSchema,
  })
  .strict();

export const ShopeeListItemFeedsResponseSchema = z
  .object({
    feeds: z.array(ShopeeOfficialFeedSchema).max(100),
  })
  .strict();

export const ShopeeItemFeedRowSchema = z
  .object({
    columns: z
      .string()
      .min(1)
      .max(5 * 1024 * 1024),
    updateType: z.string().trim().min(1).max(32).nullable(),
  })
  .strict();

export const ShopeeItemFeedPageInfoSchema = z
  .object({
    offset: z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),
    limit: z.number().int().min(1).max(SHOPEE_ITEM_FEED_MAX_PAGE_SIZE),
    totalCount: safeInt64,
    hasMore: z.boolean(),
  })
  .strict();

export const ShopeeGetItemFeedDataResponseSchema = z
  .object({
    rows: z.array(ShopeeItemFeedRowSchema).max(SHOPEE_ITEM_FEED_MAX_PAGE_SIZE),
    pageInfo: ShopeeItemFeedPageInfoSchema,
  })
  .strict();

export const ShopeeOfficialFeedColumnsSchema = z
  .object({
    itemid: z.string(),
    title: z.string(),
    price: z.string().optional().default(""),
    sale_price: z.string(),
    discount_percentage: z.string().optional().default(""),
    item_rating: z.string().optional().default(""),
    global_category1: z.string(),
    global_category2: z.string().optional().default(""),
    global_catid1: z.string().optional().default(""),
    global_catid2: z.string().optional().default(""),
    global_item_attributes: z.string().optional().default(""),
    image_link: z.string(),
    image_link_3: z.string().optional().default(""),
    product_link: z.string(),
    "product_short link": z.string().optional().default(""),
    description: z.string().optional().default(""),
  })
  .passthrough();

export type ShopeeOfficialFeed = z.infer<typeof ShopeeOfficialFeedSchema>;
export type ShopeeItemFeedPage = z.infer<
  typeof ShopeeGetItemFeedDataResponseSchema
>;

export function parseShopeeOfficialFeedColumns(
  columns: string,
): { ok: true; product: ShopeeDatafeedProduct } | { ok: false; code: string } {
  let decoded: unknown;
  try {
    decoded = JSON.parse(columns);
  } catch {
    return { ok: false, code: "SHOPEE_OPEN_API_COLUMNS_JSON_INVALID" };
  }
  const parsed = ShopeeOfficialFeedColumnsSchema.safeParse(decoded);
  if (!parsed.success) {
    return { ok: false, code: "SHOPEE_OPEN_API_COLUMNS_SCHEMA_MISMATCH" };
  }
  const normalized = normalizeShopeeDatafeedRecord({
    schema: "BRAZIL",
    record: {
      ...parsed.data,
      // The official universal-link value is provenance only. Affiliate links
      // remain exclusively generated by generateShortLink.
      "product_short link": "",
    } as ShopeeBrazilRow,
    linksVerified: false,
    source: "OPEN_API_FEED",
  });
  if (!normalized.ok) {
    return { ok: false, code: `SHOPEE_OPEN_API_${normalized.code}` };
  }
  return normalized;
}
